use crate::{ContentFamily, GenerationId, TextUnit, UnitId};
use sha2::{Digest, Sha256};

const MAX_TEXT_BYTES: usize = 1024 * 1024;
const MAX_TEXT_UNITS: usize = 16 * 1024;
const MAX_UNIT_BYTES: usize = 64 * 1024;
const UNITIZER_ID: &str = "utf8-line-chunks-65536/v1";

/// The content-family vocabulary of edition v3, derived mechanically from
/// the installed `semble` 0.5.2's own
/// `semble/index/files.py` — `_EXTENSION_TO_LANGUAGE` classified by
/// `_DOC_LANGUAGES` / `_CONFIG_LANGUAGES` / `_DATA_LANGUAGES`, exactly as
/// `semble.index.files.get_extensions()` does it (R5: the installed
/// reference's own vocabulary, not a hand-picked list). Regenerated by
/// `knowledge/work/p3-sources/source-public-w3-extractor-complete/raw/gen_vocabulary.py`,
/// whose output is asserted equal to that function's for all three
/// content types.
///
/// 342 of the reference's 347 extensions appear here. The five that do
/// not — `.csv` `.json` `.json5` `.psv` `.tsv` — are the reference's own
/// `_DATA_LANGUAGES`, which **no** `ContentType` claims, so `semble
/// --content code docs config` does not index them either. Matching that
/// is the point; adding them would be a divergence, not coverage.
///
/// Sorted by extension so `binary_search_by_key` is valid.
static EXTENSION_FAMILY: &[(&str, ContentFamily)] = &[
    (".4th", ContentFamily::Code),
    (".ada", ContentFamily::Code),
    (".adb", ContentFamily::Code),
    (".adoc", ContentFamily::Knowledge),
    (".ads", ContentFamily::Code),
    (".agda", ContentFamily::Code),
    (".al", ContentFamily::Code),
    (".as", ContentFamily::Code),
    (".asciidoc", ContentFamily::Knowledge),
    (".asm", ContentFamily::Code),
    (".astro", ContentFamily::Code),
    (".awk", ContentFamily::Code),
    (".axi", ContentFamily::Code),
    (".axs", ContentFamily::Code),
    (".bash", ContentFamily::Code),
    (".bat", ContentFamily::Code),
    (".bb", ContentFamily::Code),
    (".bbappend", ContentFamily::Code),
    (".bbclass", ContentFamily::Code),
    (".beancount", ContentFamily::Config),
    (".bib", ContentFamily::Knowledge),
    (".bicep", ContentFamily::Code),
    (".blade", ContentFamily::Code),
    (".bq", ContentFamily::Code),
    (".brs", ContentFamily::Code),
    (".bsl", ContentFamily::Code),
    (".bzl", ContentFamily::Code),
    (".c", ContentFamily::Code),
    (".c3", ContentFamily::Code),
    (".c3i", ContentFamily::Code),
    (".c3t", ContentFamily::Code),
    (".caddyfile", ContentFamily::Code),
    (".cairo", ContentFamily::Code),
    (".capnp", ContentFamily::Config),
    (".cbl", ContentFamily::Code),
    (".cc", ContentFamily::Code),
    (".cedar", ContentFamily::Code),
    (".cedarschema", ContentFamily::Config),
    (".cel", ContentFamily::Code),
    (".cfc", ContentFamily::Code),
    (".cfg", ContentFamily::Config),
    (".chatito", ContentFamily::Code),
    (".circom", ContentFamily::Code),
    (".cjs", ContentFamily::Code),
    (".ck", ContentFamily::Code),
    (".cl", ContentFamily::Code),
    (".clar", ContentFamily::Code),
    (".clj", ContentFamily::Code),
    (".cljc", ContentFamily::Code),
    (".cljs", ContentFamily::Code),
    (".cls", ContentFamily::Code),
    (".cmake", ContentFamily::Code),
    (".cmd", ContentFamily::Code),
    (".cob", ContentFamily::Code),
    (".cobol", ContentFamily::Code),
    (".conf", ContentFamily::Code),
    (".cook", ContentFamily::Config),
    (".corn", ContentFamily::Code),
    (".cpon", ContentFamily::Config),
    (".cpp", ContentFamily::Code),
    (".cr", ContentFamily::Code),
    (".cs", ContentFamily::Code),
    (".cshtml", ContentFamily::Code),
    (".css", ContentFamily::Code),
    (".cst", ContentFamily::Code),
    (".cts", ContentFamily::Code),
    (".cu", ContentFamily::Code),
    (".cuda", ContentFamily::Code),
    (".cue", ContentFamily::Code),
    (".cxx", ContentFamily::Code),
    (".cylc", ContentFamily::Code),
    (".d", ContentFamily::Code),
    (".dart", ContentFamily::Code),
    (".desktop", ContentFamily::Config),
    (".dhall", ContentFamily::Code),
    (".diff", ContentFamily::Config),
    (".dj", ContentFamily::Knowledge),
    (".dl", ContentFamily::Code),
    (".dockerfile", ContentFamily::Code),
    (".dot", ContentFamily::Code),
    (".dsp", ContentFamily::Code),
    (".dtd", ContentFamily::Config),
    (".dts", ContentFamily::Config),
    (".dtsi", ContentFamily::Config),
    (".ebnf", ContentFamily::Config),
    (".eds", ContentFamily::Code),
    (".eex", ContentFamily::Code),
    (".el", ContentFamily::Code),
    (".elm", ContentFamily::Code),
    (".elv", ContentFamily::Code),
    (".enforce", ContentFamily::Code),
    (".eps", ContentFamily::Code),
    (".erb", ContentFamily::Code),
    (".erl", ContentFamily::Code),
    (".ex", ContentFamily::Code),
    (".exs", ContentFamily::Code),
    (".f", ContentFamily::Code),
    (".f03", ContentFamily::Code),
    (".f08", ContentFamily::Code),
    (".f90", ContentFamily::Code),
    (".f95", ContentFamily::Code),
    (".fc", ContentFamily::Code),
    (".fidl", ContentFamily::Code),
    (".filter", ContentFamily::Code),
    (".fir", ContentFamily::Code),
    (".fish", ContentFamily::Code),
    (".fnl", ContentFamily::Code),
    (".fs", ContentFamily::Code),
    (".fsd", ContentFamily::Code),
    (".fsi", ContentFamily::Code),
    (".fsx", ContentFamily::Code),
    (".fth", ContentFamily::Code),
    (".fun", ContentFamily::Code),
    (".g", ContentFamily::Code),
    (".gd", ContentFamily::Code),
    (".gdshader", ContentFamily::Code),
    (".gi", ContentFamily::Code),
    (".gitattributes", ContentFamily::Config),
    (".gitignore", ContentFamily::Config),
    (".gleam", ContentFamily::Code),
    (".glsl", ContentFamily::Code),
    (".gn", ContentFamily::Code),
    (".gni", ContentFamily::Code),
    (".gnuplot", ContentFamily::Code),
    (".go", ContentFamily::Code),
    (".gotmpl", ContentFamily::Code),
    (".gp", ContentFamily::Code),
    (".gql", ContentFamily::Code),
    (".gradle", ContentFamily::Code),
    (".graphql", ContentFamily::Code),
    (".gren", ContentFamily::Code),
    (".groovy", ContentFamily::Code),
    (".gv", ContentFamily::Code),
    (".h", ContentFamily::Code),
    (".hack", ContentFamily::Code),
    (".hare", ContentFamily::Code),
    (".hbs", ContentFamily::Code),
    (".hcl", ContentFamily::Code),
    (".heex", ContentFamily::Code),
    (".hjson", ContentFamily::Config),
    (".hlsl", ContentFamily::Code),
    (".hocon", ContentFamily::Config),
    (".hoon", ContentFamily::Code),
    (".hpp", ContentFamily::Code),
    (".hrl", ContentFamily::Code),
    (".hs", ContentFamily::Code),
    (".htm", ContentFamily::Knowledge),
    (".html", ContentFamily::Knowledge),
    (".http", ContentFamily::Code),
    (".hurl", ContentFamily::Code),
    (".hx", ContentFamily::Code),
    (".hxx", ContentFamily::Code),
    (".idr", ContentFamily::Code),
    (".inc", ContentFamily::Code),
    (".ini", ContentFamily::Config),
    (".ino", ContentFamily::Code),
    (".ispc", ContentFamily::Code),
    (".j2", ContentFamily::Code),
    (".jai", ContentFamily::Code),
    (".janet", ContentFamily::Code),
    (".java", ContentFamily::Code),
    (".jinja2", ContentFamily::Code),
    (".jl", ContentFamily::Code),
    (".journal", ContentFamily::Config),
    (".jq", ContentFamily::Code),
    (".js", ContentFamily::Code),
    (".jsonnet", ContentFamily::Code),
    (".jsx", ContentFamily::Code),
    (".just", ContentFamily::Code),
    (".k", ContentFamily::Code),
    (".kdl", ContentFamily::Config),
    (".kt", ContentFamily::Code),
    (".kts", ContentFamily::Code),
    (".lc", ContentFamily::Code),
    (".ldg", ContentFamily::Config),
    (".lds", ContentFamily::Code),
    (".lean", ContentFamily::Code),
    (".ledger", ContentFamily::Config),
    (".leex", ContentFamily::Code),
    (".less", ContentFamily::Code),
    (".libsonnet", ContentFamily::Code),
    (".liquid", ContentFamily::Code),
    (".lisp", ContentFamily::Code),
    (".ll", ContentFamily::Code),
    (".lua", ContentFamily::Code),
    (".luau", ContentFamily::Code),
    (".m", ContentFamily::Code),
    (".magik", ContentFamily::Code),
    (".makefile", ContentFamily::Code),
    (".markdown", ContentFamily::Knowledge),
    (".matlab", ContentFamily::Code),
    (".md", ContentFamily::Knowledge),
    (".mermaid", ContentFamily::Knowledge),
    (".meson", ContentFamily::Code),
    (".mjs", ContentFamily::Code),
    (".mk", ContentFamily::Code),
    (".ml", ContentFamily::Code),
    (".mli", ContentFamily::Code),
    (".mlir", ContentFamily::Code),
    (".mll", ContentFamily::Code),
    (".mmd", ContentFamily::Knowledge),
    (".mod", ContentFamily::Config),
    (".mojo", ContentFamily::Code),
    (".move", ContentFamily::Code),
    (".mts", ContentFamily::Code),
    (".nasm", ContentFamily::Code),
    (".ncl", ContentFamily::Code),
    (".nginx", ContentFamily::Code),
    (".nim", ContentFamily::Code),
    (".nims", ContentFamily::Code),
    (".ninja", ContentFamily::Code),
    (".nix", ContentFamily::Code),
    (".norg", ContentFamily::Knowledge),
    (".nqc", ContentFamily::Code),
    (".nu", ContentFamily::Code),
    (".nut", ContentFamily::Code),
    (".odin", ContentFamily::Code),
    (".org", ContentFamily::Knowledge),
    (".p", ContentFamily::Code),
    (".pas", ContentFamily::Code),
    (".patch", ContentFamily::Config),
    (".pbtxt", ContentFamily::Config),
    (".pem", ContentFamily::Config),
    (".pgn", ContentFamily::Config),
    (".php", ContentFamily::Code),
    (".pkl", ContentFamily::Code),
    (".pl", ContentFamily::Code),
    (".plt", ContentFamily::Code),
    (".pm", ContentFamily::Code),
    (".po", ContentFamily::Knowledge),
    (".pony", ContentFamily::Code),
    (".pot", ContentFamily::Knowledge),
    (".pp", ContentFamily::Code),
    (".prisma", ContentFamily::Code),
    (".pro", ContentFamily::Code),
    (".promql", ContentFamily::Code),
    (".properties", ContentFamily::Config),
    (".proto", ContentFamily::Config),
    (".prql", ContentFamily::Code),
    (".ps", ContentFamily::Code),
    (".ps1", ContentFamily::Code),
    (".psd1", ContentFamily::Code),
    (".psm1", ContentFamily::Code),
    (".pug", ContentFamily::Code),
    (".purs", ContentFamily::Code),
    (".py", ContentFamily::Code),
    (".pyi", ContentFamily::Code),
    (".pyw", ContentFamily::Code),
    (".ql", ContentFamily::Code),
    (".qml", ContentFamily::Code),
    (".r", ContentFamily::Code),
    (".rasi", ContentFamily::Code),
    (".razor", ContentFamily::Code),
    (".rb", ContentFamily::Code),
    (".rbs", ContentFamily::Code),
    (".re", ContentFamily::Code),
    (".rego", ContentFamily::Code),
    (".res", ContentFamily::Code),
    (".resi", ContentFamily::Code),
    (".rkt", ContentFamily::Code),
    (".robot", ContentFamily::Code),
    (".roc", ContentFamily::Code),
    (".ron", ContentFamily::Config),
    (".rs", ContentFamily::Code),
    (".rst", ContentFamily::Knowledge),
    (".rtf", ContentFamily::Knowledge),
    (".s", ContentFamily::Code),
    (".scad", ContentFamily::Code),
    (".scala", ContentFamily::Code),
    (".scm", ContentFamily::Code),
    (".scss", ContentFamily::Code),
    (".sh", ContentFamily::Code),
    (".shtml", ContentFamily::Code),
    (".sig", ContentFamily::Code),
    (".slang", ContentFamily::Code),
    (".smali", ContentFamily::Code),
    (".smithy", ContentFamily::Config),
    (".smk", ContentFamily::Code),
    (".sml", ContentFamily::Code),
    (".sol", ContentFamily::Code),
    (".sp", ContentFamily::Code),
    (".sparql", ContentFamily::Code),
    (".sql", ContentFamily::Code),
    (".squirrel", ContentFamily::Code),
    (".st", ContentFamily::Code),
    (".stan", ContentFamily::Code),
    (".star", ContentFamily::Code),
    (".sv", ContentFamily::Code),
    (".svelte", ContentFamily::Code),
    (".svh", ContentFamily::Code),
    (".sw", ContentFamily::Code),
    (".swift", ContentFamily::Code),
    (".tact", ContentFamily::Code),
    (".tal", ContentFamily::Code),
    (".tape", ContentFamily::Code),
    (".tcl", ContentFamily::Code),
    (".td", ContentFamily::Code),
    (".templ", ContentFamily::Code),
    (".tera", ContentFamily::Code),
    (".tex", ContentFamily::Knowledge),
    (".textproto", ContentFamily::Config),
    (".tf", ContentFamily::Code),
    (".tfvars", ContentFamily::Code),
    (".thrift", ContentFamily::Config),
    (".tl", ContentFamily::Code),
    (".tla", ContentFamily::Code),
    (".todotxt", ContentFamily::Config),
    (".toml", ContentFamily::Config),
    (".tres", ContentFamily::Config),
    (".trigger", ContentFamily::Code),
    (".ts", ContentFamily::Code),
    (".tscn", ContentFamily::Config),
    (".tsconfig", ContentFamily::Code),
    (".tsp", ContentFamily::Config),
    (".tsx", ContentFamily::Code),
    (".ttl", ContentFamily::Config),
    (".twig", ContentFamily::Code),
    (".typoscript", ContentFamily::Code),
    (".typst", ContentFamily::Code),
    (".v", ContentFamily::Code),
    (".vb", ContentFamily::Code),
    (".verilog", ContentFamily::Code),
    (".vhd", ContentFamily::Code),
    (".vhdl", ContentFamily::Code),
    (".vim", ContentFamily::Code),
    (".vrl", ContentFamily::Code),
    (".vue", ContentFamily::Code),
    (".w", ContentFamily::Code),
    (".wast", ContentFamily::Code),
    (".wat", ContentFamily::Code),
    (".wgsl", ContentFamily::Code),
    (".wit", ContentFamily::Config),
    (".wl", ContentFamily::Code),
    (".xml", ContentFamily::Config),
    (".xsl", ContentFamily::Config),
    (".xslt", ContentFamily::Config),
    (".yaml", ContentFamily::Config),
    (".yml", ContentFamily::Config),
    (".yuck", ContentFamily::Code),
    (".zig", ContentFamily::Code),
    (".ziggy", ContentFamily::Code),
    (".zsh", ContentFamily::Code),
];

/// Python `PurePath.suffix`, byte-for-byte, over a repository-relative
/// path's final component, ASCII-lowercased — the exact rule
/// `semble.index.files.detect_language` applies
/// (`_EXTENSION_TO_LANGUAGE.get(file_name.suffix.lower())`).
///
/// The details matter and are the reference's, not ours: a dotfile like
/// `.gitignore` has **no** suffix (the dot is at index 0), so it is not
/// matched by the `.gitignore` row — only `something.gitignore` is; and
/// a trailing dot (`a.`) also yields no suffix. Getting either wrong
/// would silently index or skip whole classes of file relative to the
/// control we are measuring against.
fn path_suffix_lowercase(path: &[u8]) -> Option<String> {
    let name = match path.iter().rposition(|byte| *byte == b'/') {
        Some(slash) => &path[slash + 1..],
        None => path,
    };
    if name == b"." || name == b".." {
        return None;
    }
    let dot = name.iter().rposition(|byte| *byte == b'.')?;
    if dot == 0 || dot + 1 >= name.len() {
        return None;
    }
    Some(String::from_utf8_lossy(&name[dot..]).to_ascii_lowercase())
}

/// Which extraction edition produced (or must validate) a generation.
///
/// P3 W3 extractor completion (`W3-EXTRACTOR-COMPLETION.md`, under
/// ruling 0095): the family vocabulary is a property of the *edition*
/// recorded on each generation, never a single global rule. That is what
/// lets `v3` widen coverage while every `v2` generation already staged in
/// an estate keeps validating and resolving byte-for-byte — the brief's
/// "preserve old generation objects and exact historical coordinate
/// resolution". `AtlasStore::validate_generation` resolves the edition
/// from `generation.extractor_set` and asks *it* for the family, rather
/// than re-deriving families from today's default.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExtractorEdition {
    /// Historical: Rust and Markdown only. Never produced again; still
    /// validated and resolved.
    RustMarkdownV2,
    /// Historical: Markdown only.
    MarkdownOnlyV2,
    /// Current. Text line-chunk extraction over the complete
    /// `semble` 0.5.2 code/docs/config vocabulary (`EXTENSION_FAMILY`).
    ///
    /// The identity says `text-line-chunks` deliberately. This edition
    /// widens *which files are admitted*, not how they are cut: the
    /// unitizer is still `utf8-line-chunks-65536/v1`, so a unit is a
    /// bounded run of bytes on one line and nothing here claims to know
    /// a function, a class or a section. A reader must be able to tell
    /// that from the identity alone, without reading this file
    /// (`W3-EXTRACTOR-COMPLETION.md`: "Do not infer semantic syntax
    /// claims from line chunks ... keep extractor identities explicit").
    ContentFamiliesV3,
}

impl ExtractorEdition {
    pub(crate) fn id(self) -> &'static str {
        match self {
            Self::RustMarkdownV2 => "utf8-lines/rust-markdown+utf8-line-chunks-65536/v2",
            Self::MarkdownOnlyV2 => "utf8-lines/markdown+utf8-line-chunks-65536/v2",
            Self::ContentFamiliesV3 => {
                "text-line-chunks/utf8-line-chunks-65536+semble-0.5.2-content-families/v3"
            }
        }
    }
    /// The inverse of `id`, for validating a generation against the
    /// edition it says produced it. An `extractor_set` naming no known
    /// edition is refused rather than silently validated under today's
    /// rules.
    pub(crate) fn from_id(id: &str) -> Option<Self> {
        [
            Self::RustMarkdownV2,
            Self::MarkdownOnlyV2,
            Self::ContentFamiliesV3,
        ]
        .into_iter()
        .find(|edition| edition.id() == id)
    }
    pub(crate) fn family(self, path: &[u8]) -> Option<ContentFamily> {
        match self {
            Self::RustMarkdownV2 => {
                if path.ends_with(b".md") {
                    Some(ContentFamily::Knowledge)
                } else if path.ends_with(b".rs") {
                    Some(ContentFamily::Code)
                } else {
                    None
                }
            }
            Self::MarkdownOnlyV2 => {
                if path.ends_with(b".md") {
                    Some(ContentFamily::Knowledge)
                } else {
                    None
                }
            }
            Self::ContentFamiliesV3 => {
                let suffix = path_suffix_lowercase(path)?;
                EXTENSION_FAMILY
                    .binary_search_by_key(&suffix.as_str(), |(ext, _)| ext)
                    .ok()
                    .map(|index| EXTENSION_FAMILY[index].1)
            }
        }
    }
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExtractorPolicy {
    edition: ExtractorEdition,
}
impl Default for ExtractorPolicy {
    fn default() -> Self {
        Self {
            edition: ExtractorEdition::ContentFamiliesV3,
        }
    }
}
impl ExtractorPolicy {
    pub fn markdown_only() -> Self {
        Self {
            edition: ExtractorEdition::MarkdownOnlyV2,
        }
    }
    /// The historical Rust+Markdown edition, kept constructible so a test
    /// can stage a `v2` generation on purpose and prove it still
    /// validates and resolves under the current binary.
    pub fn rust_markdown_v2() -> Self {
        Self {
            edition: ExtractorEdition::RustMarkdownV2,
        }
    }
    pub(crate) fn id(&self) -> &str {
        self.edition.id()
    }
    pub(crate) fn supports(&self, path: &[u8]) -> bool {
        self.family(path).is_some()
    }
    pub(crate) fn family(&self, path: &[u8]) -> Option<ContentFamily> {
        self.edition.family(path)
    }
    pub(crate) fn excluded(path: &[u8]) -> bool {
        path.split(|b| *b == b'/')
            .any(|part| part == b".git" || part == b".env" || part == b"secret")
            || path.ends_with(b".pem")
            || path.ends_with(b".key")
    }
    pub(crate) fn units(
        &self,
        generation: &GenerationId,
        path: &[u8],
        object_id: &str,
        bytes: &[u8],
    ) -> Result<Vec<TextUnit>, &'static str> {
        if bytes.len() > MAX_TEXT_BYTES {
            return Err("text blob exceeds bounded extractor size");
        }
        let text = std::str::from_utf8(bytes).map_err(|_| "text blob is not valid UTF-8")?;
        let family = self
            .family(path)
            .ok_or("path has no configured content family")?;
        let mut units = Vec::new();
        let mut start = 0usize;
        let mut line = 1u64;
        for (index, byte) in bytes.iter().enumerate() {
            if *byte == b'\n' {
                push_line_chunks(
                    &mut units,
                    text,
                    start,
                    index + 1,
                    line,
                    generation,
                    path,
                    object_id,
                    family,
                )?;
                start = index + 1;
                line += 1;
            }
        }
        if start < bytes.len() || bytes.is_empty() {
            push_line_chunks(
                &mut units,
                text,
                start,
                bytes.len(),
                line,
                generation,
                path,
                object_id,
                family,
            )?;
        }
        Ok(units)
    }
    pub(crate) fn generation_id(
        source: &str,
        revision: &str,
        content: &str,
        extractor: &str,
    ) -> String {
        let mut h = Sha256::new();
        for part in [
            b"wirk-atlas-generation/v1".as_slice(),
            source.as_bytes(),
            revision.as_bytes(),
            content.as_bytes(),
            extractor.as_bytes(),
            b"git-tree-policy/v1",
        ] {
            h.update((part.len() as u64).to_be_bytes());
            h.update(part);
        }
        format!("g-{}", hex(&h.finalize()))
    }

    pub(crate) fn unit_id(
        generation: &GenerationId,
        path: &[u8],
        object_id: &str,
        family: ContentFamily,
        byte_start: u64,
        byte_end: u64,
    ) -> UnitId {
        let mut h = Sha256::new();
        for part in [
            b"wirk-atlas-unit/v1".as_slice(),
            generation.0.as_bytes(),
            path,
            object_id.as_bytes(),
            match family {
                ContentFamily::Code => b"code".as_slice(),
                ContentFamily::Knowledge => b"knowledge".as_slice(),
                // New in edition v3. A distinct tag, so a `config` unit
                // can never collide with a `code`/`knowledge` unit id.
                ContentFamily::Config => b"config".as_slice(),
            },
            byte_start.to_string().as_bytes(),
            byte_end.to_string().as_bytes(),
            UNITIZER_ID.as_bytes(),
        ] {
            h.update((part.len() as u64).to_be_bytes());
            h.update(part);
        }
        UnitId(format!("u-{}", hex(&h.finalize())))
    }
}

#[allow(clippy::too_many_arguments)]
fn push_line_chunks(
    units: &mut Vec<TextUnit>,
    text: &str,
    line_start: usize,
    line_end: usize,
    line: u64,
    generation: &GenerationId,
    path: &[u8],
    object_id: &str,
    family: ContentFamily,
) -> Result<(), &'static str> {
    if line_start == line_end {
        push_unit(units, generation, path, object_id, family, 0, 0, line)?;
        return Ok(());
    }
    let mut start = line_start;
    while start < line_end {
        let mut end = (start + MAX_UNIT_BYTES).min(line_end);
        while end > start && !text.is_char_boundary(end) {
            end -= 1;
        }
        if end == start {
            return Err("UTF-8 codepoint exceeds unit size budget");
        }
        push_unit(units, generation, path, object_id, family, start, end, line)?;
        start = end;
    }
    Ok(())
}

#[allow(clippy::too_many_arguments)]
fn push_unit(
    units: &mut Vec<TextUnit>,
    generation: &GenerationId,
    path: &[u8],
    object_id: &str,
    family: ContentFamily,
    byte_start: usize,
    byte_end: usize,
    line: u64,
) -> Result<(), &'static str> {
    if units.len() == MAX_TEXT_UNITS {
        return Err("text blob exceeds bounded unit count");
    }
    units.push(TextUnit {
        id: ExtractorPolicy::unit_id(
            generation,
            path,
            object_id,
            family,
            byte_start as u64,
            byte_end as u64,
        ),
        family,
        unitizer: UNITIZER_ID.into(),
        byte_start: byte_start as u64,
        byte_end: byte_end as u64,
        line_start: line,
        line_end: line,
    });
    Ok(())
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}
