use crate::{ContentFamily, GenerationId, TextUnit, UnitId};
use sha2::{Digest, Sha256};

/// The byte budget one retrieval unit is cut to, and the only number in
/// this reader that survives rulings 0398/0401/0403's removal of
/// size-derived refusal.
///
/// It refuses nothing. It is the unitizer's own chunk width — the
/// "65536" every unitizer id here is literally named after
/// (`UNITIZER_ID`, `MULTILINE_UNITIZER_ID`,
/// `DOCUMENT_MARKDOWN_UNITIZER_ID`) — so it is part of what a staged
/// generation recorded and what `AtlasStore::validate_generation`
/// re-derives a unit's identity against, not a decision about whether
/// admitted text may be read. Larger text simply becomes more units.
const MAX_UNIT_BYTES: usize = 64 * 1024;
const UNITIZER_ID: &str = "utf8-line-chunks-65536/v1";
/// Edition v4's unitizer. `utf8-line-chunks-65536/v1` never packed more
/// than one line into a unit despite its own "65536" name — a file with
/// more lines than `MAX_TEXT_UNITS` (e.g. `wirk/src/wirkd/server.rs` at
/// 16,857 lines) hit the unit-count budget while each unit sat far under
/// the byte budget it was named for. This unitizer packs consecutive
/// short lines into one unit up to the same 65536-byte budget — the
/// budget the name always promised — so unit count now tracks bytes, not
/// lines. A line that alone exceeds the budget still splits exactly as
/// `v1` did. See `W4-EXTRACTOR-MULTILINE.md`.
const MULTILINE_UNITIZER_ID: &str = "utf8-multiline-chunks-65536/v1";
/// Edition v5's document unitizer: the same byte-budget chunker
/// `MULTILINE_UNITIZER_ID` names, applied to the Markdown `anydoc` 0.2.4
/// renders from an Office/PDF/CSV file rather than to the file's own
/// bytes. Distinct from `MULTILINE_UNITIZER_ID` on purpose — a reader
/// must be able to tell from this id alone that a unit's offsets index
/// converted Markdown, not the original document
/// (`ContentFamily::Document`'s own doc comment carries the rest).
const DOCUMENT_MARKDOWN_UNITIZER_ID: &str = "anydoc-0.2.4-markdown+utf8-multiline-chunks-65536/v1";

/// The content-family vocabulary of edition v3, derived mechanically from
/// the installed `semble` 0.5.2's own
/// `semble/index/files.py` — `_EXTENSION_TO_LANGUAGE` classified by
/// `_DOC_LANGUAGES` / `_CONFIG_LANGUAGES` / `_DATA_LANGUAGES`, exactly as
/// `semble.index.files.get_extensions()` does it (R5: the installed
/// reference's own vocabulary, not a hand-picked list). Regenerated by
/// `knowledge/work/p3-sources/source-public-w3-extractor-complete/raw/gen_vocabulary.py`,
/// whose output is asserted equal to that function's for all three
/// content types.
///
/// 342 of the reference's 347 extensions appear here. The five that do
/// not — `.csv` `.json` `.json5` `.psv` `.tsv` — are the reference's own
/// `_DATA_LANGUAGES`, which **no** `ContentType` claims, so `semble
/// --content code docs config` does not index them either. Matching that
/// is the point; adding them would be a divergence, not coverage.
///
/// Sorted by extension so `binary_search_by_key` is valid.
static EXTENSION_FAMILY: &[(&str, ContentFamily)] = &[
    (".4th", ContentFamily::Code),
    (".ada", ContentFamily::Code),
    (".adb", ContentFamily::Code),
    (".adoc", ContentFamily::Knowledge),
    (".ads", ContentFamily::Code),
    (".agda", ContentFamily::Code),
    (".al", ContentFamily::Code),
    (".as", ContentFamily::Code),
    (".asciidoc", ContentFamily::Knowledge),
    (".asm", ContentFamily::Code),
    (".astro", ContentFamily::Code),
    (".awk", ContentFamily::Code),
    (".axi", ContentFamily::Code),
    (".axs", ContentFamily::Code),
    (".bash", ContentFamily::Code),
    (".bat", ContentFamily::Code),
    (".bb", ContentFamily::Code),
    (".bbappend", ContentFamily::Code),
    (".bbclass", ContentFamily::Code),
    (".beancount", ContentFamily::Config),
    (".bib", ContentFamily::Knowledge),
    (".bicep", ContentFamily::Code),
    (".blade", ContentFamily::Code),
    (".bq", ContentFamily::Code),
    (".brs", ContentFamily::Code),
    (".bsl", ContentFamily::Code),
    (".bzl", ContentFamily::Code),
    (".c", ContentFamily::Code),
    (".c3", ContentFamily::Code),
    (".c3i", ContentFamily::Code),
    (".c3t", ContentFamily::Code),
    (".caddyfile", ContentFamily::Code),
    (".cairo", ContentFamily::Code),
    (".capnp", ContentFamily::Config),
    (".cbl", ContentFamily::Code),
    (".cc", ContentFamily::Code),
    (".cedar", ContentFamily::Code),
    (".cedarschema", ContentFamily::Config),
    (".cel", ContentFamily::Code),
    (".cfc", ContentFamily::Code),
    (".cfg", ContentFamily::Config),
    (".chatito", ContentFamily::Code),
    (".circom", ContentFamily::Code),
    (".cjs", ContentFamily::Code),
    (".ck", ContentFamily::Code),
    (".cl", ContentFamily::Code),
    (".clar", ContentFamily::Code),
    (".clj", ContentFamily::Code),
    (".cljc", ContentFamily::Code),
    (".cljs", ContentFamily::Code),
    (".cls", ContentFamily::Code),
    (".cmake", ContentFamily::Code),
    (".cmd", ContentFamily::Code),
    (".cob", ContentFamily::Code),
    (".cobol", ContentFamily::Code),
    (".conf", ContentFamily::Code),
    (".cook", ContentFamily::Config),
    (".corn", ContentFamily::Code),
    (".cpon", ContentFamily::Config),
    (".cpp", ContentFamily::Code),
    (".cr", ContentFamily::Code),
    (".cs", ContentFamily::Code),
    (".cshtml", ContentFamily::Code),
    (".css", ContentFamily::Code),
    (".cst", ContentFamily::Code),
    (".cts", ContentFamily::Code),
    (".cu", ContentFamily::Code),
    (".cuda", ContentFamily::Code),
    (".cue", ContentFamily::Code),
    (".cxx", ContentFamily::Code),
    (".cylc", ContentFamily::Code),
    (".d", ContentFamily::Code),
    (".dart", ContentFamily::Code),
    (".desktop", ContentFamily::Config),
    (".dhall", ContentFamily::Code),
    (".diff", ContentFamily::Config),
    (".dj", ContentFamily::Knowledge),
    (".dl", ContentFamily::Code),
    (".dockerfile", ContentFamily::Code),
    (".dot", ContentFamily::Code),
    (".dsp", ContentFamily::Code),
    (".dtd", ContentFamily::Config),
    (".dts", ContentFamily::Config),
    (".dtsi", ContentFamily::Config),
    (".ebnf", ContentFamily::Config),
    (".eds", ContentFamily::Code),
    (".eex", ContentFamily::Code),
    (".el", ContentFamily::Code),
    (".elm", ContentFamily::Code),
    (".elv", ContentFamily::Code),
    (".enforce", ContentFamily::Code),
    (".eps", ContentFamily::Code),
    (".erb", ContentFamily::Code),
    (".erl", ContentFamily::Code),
    (".ex", ContentFamily::Code),
    (".exs", ContentFamily::Code),
    (".f", ContentFamily::Code),
    (".f03", ContentFamily::Code),
    (".f08", ContentFamily::Code),
    (".f90", ContentFamily::Code),
    (".f95", ContentFamily::Code),
    (".fc", ContentFamily::Code),
    (".fidl", ContentFamily::Code),
    (".filter", ContentFamily::Code),
    (".fir", ContentFamily::Code),
    (".fish", ContentFamily::Code),
    (".fnl", ContentFamily::Code),
    (".fs", ContentFamily::Code),
    (".fsd", ContentFamily::Code),
    (".fsi", ContentFamily::Code),
    (".fsx", ContentFamily::Code),
    (".fth", ContentFamily::Code),
    (".fun", ContentFamily::Code),
    (".g", ContentFamily::Code),
    (".gd", ContentFamily::Code),
    (".gdshader", ContentFamily::Code),
    (".gi", ContentFamily::Code),
    (".gitattributes", ContentFamily::Config),
    (".gitignore", ContentFamily::Config),
    (".gleam", ContentFamily::Code),
    (".glsl", ContentFamily::Code),
    (".gn", ContentFamily::Code),
    (".gni", ContentFamily::Code),
    (".gnuplot", ContentFamily::Code),
    (".go", ContentFamily::Code),
    (".gotmpl", ContentFamily::Code),
    (".gp", ContentFamily::Code),
    (".gql", ContentFamily::Code),
    (".gradle", ContentFamily::Code),
    (".graphql", ContentFamily::Code),
    (".gren", ContentFamily::Code),
    (".groovy", ContentFamily::Code),
    (".gv", ContentFamily::Code),
    (".h", ContentFamily::Code),
    (".hack", ContentFamily::Code),
    (".hare", ContentFamily::Code),
    (".hbs", ContentFamily::Code),
    (".hcl", ContentFamily::Code),
    (".heex", ContentFamily::Code),
    (".hjson", ContentFamily::Config),
    (".hlsl", ContentFamily::Code),
    (".hocon", ContentFamily::Config),
    (".hoon", ContentFamily::Code),
    (".hpp", ContentFamily::Code),
    (".hrl", ContentFamily::Code),
    (".hs", ContentFamily::Code),
    (".htm", ContentFamily::Knowledge),
    (".html", ContentFamily::Knowledge),
    (".http", ContentFamily::Code),
    (".hurl", ContentFamily::Code),
    (".hx", ContentFamily::Code),
    (".hxx", ContentFamily::Code),
    (".idr", ContentFamily::Code),
    (".inc", ContentFamily::Code),
    (".ini", ContentFamily::Config),
    (".ino", ContentFamily::Code),
    (".ispc", ContentFamily::Code),
    (".j2", ContentFamily::Code),
    (".jai", ContentFamily::Code),
    (".janet", ContentFamily::Code),
    (".java", ContentFamily::Code),
    (".jinja2", ContentFamily::Code),
    (".jl", ContentFamily::Code),
    (".journal", ContentFamily::Config),
    (".jq", ContentFamily::Code),
    (".js", ContentFamily::Code),
    (".jsonnet", ContentFamily::Code),
    (".jsx", ContentFamily::Code),
    (".just", ContentFamily::Code),
    (".k", ContentFamily::Code),
    (".kdl", ContentFamily::Config),
    (".kt", ContentFamily::Code),
    (".kts", ContentFamily::Code),
    (".lc", ContentFamily::Code),
    (".ldg", ContentFamily::Config),
    (".lds", ContentFamily::Code),
    (".lean", ContentFamily::Code),
    (".ledger", ContentFamily::Config),
    (".leex", ContentFamily::Code),
    (".less", ContentFamily::Code),
    (".libsonnet", ContentFamily::Code),
    (".liquid", ContentFamily::Code),
    (".lisp", ContentFamily::Code),
    (".ll", ContentFamily::Code),
    (".lua", ContentFamily::Code),
    (".luau", ContentFamily::Code),
    (".m", ContentFamily::Code),
    (".magik", ContentFamily::Code),
    (".makefile", ContentFamily::Code),
    (".markdown", ContentFamily::Knowledge),
    (".matlab", ContentFamily::Code),
    (".md", ContentFamily::Knowledge),
    (".mermaid", ContentFamily::Knowledge),
    (".meson", ContentFamily::Code),
    (".mjs", ContentFamily::Code),
    (".mk", ContentFamily::Code),
    (".ml", ContentFamily::Code),
    (".mli", ContentFamily::Code),
    (".mlir", ContentFamily::Code),
    (".mll", ContentFamily::Code),
    (".mmd", ContentFamily::Knowledge),
    (".mod", ContentFamily::Config),
    (".mojo", ContentFamily::Code),
    (".move", ContentFamily::Code),
    (".mts", ContentFamily::Code),
    (".nasm", ContentFamily::Code),
    (".ncl", ContentFamily::Code),
    (".nginx", ContentFamily::Code),
    (".nim", ContentFamily::Code),
    (".nims", ContentFamily::Code),
    (".ninja", ContentFamily::Code),
    (".nix", ContentFamily::Code),
    (".norg", ContentFamily::Knowledge),
    (".nqc", ContentFamily::Code),
    (".nu", ContentFamily::Code),
    (".nut", ContentFamily::Code),
    (".odin", ContentFamily::Code),
    (".org", ContentFamily::Knowledge),
    (".p", ContentFamily::Code),
    (".pas", ContentFamily::Code),
    (".patch", ContentFamily::Config),
    (".pbtxt", ContentFamily::Config),
    (".pem", ContentFamily::Config),
    (".pgn", ContentFamily::Config),
    (".php", ContentFamily::Code),
    (".pkl", ContentFamily::Code),
    (".pl", ContentFamily::Code),
    (".plt", ContentFamily::Code),
    (".pm", ContentFamily::Code),
    (".po", ContentFamily::Knowledge),
    (".pony", ContentFamily::Code),
    (".pot", ContentFamily::Knowledge),
    (".pp", ContentFamily::Code),
    (".prisma", ContentFamily::Code),
    (".pro", ContentFamily::Code),
    (".promql", ContentFamily::Code),
    (".properties", ContentFamily::Config),
    (".proto", ContentFamily::Config),
    (".prql", ContentFamily::Code),
    (".ps", ContentFamily::Code),
    (".ps1", ContentFamily::Code),
    (".psd1", ContentFamily::Code),
    (".psm1", ContentFamily::Code),
    (".pug", ContentFamily::Code),
    (".purs", ContentFamily::Code),
    (".py", ContentFamily::Code),
    (".pyi", ContentFamily::Code),
    (".pyw", ContentFamily::Code),
    (".ql", ContentFamily::Code),
    (".qml", ContentFamily::Code),
    (".r", ContentFamily::Code),
    (".rasi", ContentFamily::Code),
    (".razor", ContentFamily::Code),
    (".rb", ContentFamily::Code),
    (".rbs", ContentFamily::Code),
    (".re", ContentFamily::Code),
    (".rego", ContentFamily::Code),
    (".res", ContentFamily::Code),
    (".resi", ContentFamily::Code),
    (".rkt", ContentFamily::Code),
    (".robot", ContentFamily::Code),
    (".roc", ContentFamily::Code),
    (".ron", ContentFamily::Config),
    (".rs", ContentFamily::Code),
    (".rst", ContentFamily::Knowledge),
    (".rtf", ContentFamily::Knowledge),
    (".s", ContentFamily::Code),
    (".scad", ContentFamily::Code),
    (".scala", ContentFamily::Code),
    (".scm", ContentFamily::Code),
    (".scss", ContentFamily::Code),
    (".sh", ContentFamily::Code),
    (".shtml", ContentFamily::Code),
    (".sig", ContentFamily::Code),
    (".slang", ContentFamily::Code),
    (".smali", ContentFamily::Code),
    (".smithy", ContentFamily::Config),
    (".smk", ContentFamily::Code),
    (".sml", ContentFamily::Code),
    (".sol", ContentFamily::Code),
    (".sp", ContentFamily::Code),
    (".sparql", ContentFamily::Code),
    (".sql", ContentFamily::Code),
    (".squirrel", ContentFamily::Code),
    (".st", ContentFamily::Code),
    (".stan", ContentFamily::Code),
    (".star", ContentFamily::Code),
    (".sv", ContentFamily::Code),
    (".svelte", ContentFamily::Code),
    (".svh", ContentFamily::Code),
    (".sw", ContentFamily::Code),
    (".swift", ContentFamily::Code),
    (".tact", ContentFamily::Code),
    (".tal", ContentFamily::Code),
    (".tape", ContentFamily::Code),
    (".tcl", ContentFamily::Code),
    (".td", ContentFamily::Code),
    (".templ", ContentFamily::Code),
    (".tera", ContentFamily::Code),
    (".tex", ContentFamily::Knowledge),
    (".textproto", ContentFamily::Config),
    (".tf", ContentFamily::Code),
    (".tfvars", ContentFamily::Code),
    (".thrift", ContentFamily::Config),
    (".tl", ContentFamily::Code),
    (".tla", ContentFamily::Code),
    (".todotxt", ContentFamily::Config),
    (".toml", ContentFamily::Config),
    (".tres", ContentFamily::Config),
    (".trigger", ContentFamily::Code),
    (".ts", ContentFamily::Code),
    (".tscn", ContentFamily::Config),
    (".tsconfig", ContentFamily::Code),
    (".tsp", ContentFamily::Config),
    (".tsx", ContentFamily::Code),
    (".ttl", ContentFamily::Config),
    (".twig", ContentFamily::Code),
    (".typoscript", ContentFamily::Code),
    (".typst", ContentFamily::Code),
    (".v", ContentFamily::Code),
    (".vb", ContentFamily::Code),
    (".verilog", ContentFamily::Code),
    (".vhd", ContentFamily::Code),
    (".vhdl", ContentFamily::Code),
    (".vim", ContentFamily::Code),
    (".vrl", ContentFamily::Code),
    (".vue", ContentFamily::Code),
    (".w", ContentFamily::Code),
    (".wast", ContentFamily::Code),
    (".wat", ContentFamily::Code),
    (".wgsl", ContentFamily::Code),
    (".wit", ContentFamily::Config),
    (".wl", ContentFamily::Code),
    (".xml", ContentFamily::Config),
    (".xsl", ContentFamily::Config),
    (".xslt", ContentFamily::Config),
    (".yaml", ContentFamily::Config),
    (".yml", ContentFamily::Config),
    (".yuck", ContentFamily::Code),
    (".zig", ContentFamily::Code),
    (".ziggy", ContentFamily::Code),
    (".zsh", ContentFamily::Code),
];

/// Python `PurePath.suffix`, byte-for-byte, over a repository-relative
/// path's final component, ASCII-lowercased — the exact rule
/// `semble.index.files.detect_language` applies
/// (`_EXTENSION_TO_LANGUAGE.get(file_name.suffix.lower())`).
///
/// The details matter and are the reference's, not ours: a dotfile like
/// `.gitignore` has **no** suffix (the dot is at index 0), so it is not
/// matched by the `.gitignore` row — only `something.gitignore` is; and
/// a trailing dot (`a.`) also yields no suffix. Getting either wrong
/// would silently index or skip whole classes of file relative to the
/// control we are measuring against.
fn path_suffix_lowercase(path: &[u8]) -> Option<String> {
    let name = match path.iter().rposition(|byte| *byte == b'/') {
        Some(slash) => &path[slash + 1..],
        None => path,
    };
    if name == b"." || name == b".." {
        return None;
    }
    let dot = name.iter().rposition(|byte| *byte == b'.')?;
    if dot == 0 || dot + 1 >= name.len() {
        return None;
    }
    Some(String::from_utf8_lossy(&name[dot..]).to_ascii_lowercase())
}

/// The one plain-text extension the generated vocabulary above does not
/// name, and cannot: the reference answers "which language is this", and
/// `.txt` names no language, so it has no row there. The question this
/// module's callers actually ask the vocabulary is the different one —
/// "is this plain text" — and for that question `.txt` is the plainest
/// answer there is.
///
/// Kept out of `EXTENSION_FAMILY` and carried by the edition instead,
/// because that table is the vocabulary editions v3 through v6 all read:
/// a row added there widens every one of them retroactively, and a
/// generation an older binary recorded under the old answer stops
/// validating and stops resolving. Editions exist so a vocabulary can
/// change without that happening, so this belongs to one edition rather
/// than to the shared table.
const PLAIN_TEXT_EXTENSION: (&str, ContentFamily) = (".txt", ContentFamily::Knowledge);

/// Whether `path`'s extension names one of the plain-text content
/// families (`Code`/`Knowledge`/`Config`) **in `edition`'s own
/// vocabulary**. `crate::document` asks this to decide whether a
/// resource's bytes may be sniffed at all: a path the text vocabulary
/// already claims is read as text, and nothing about its content changes
/// that. That is what keeps ordinary Markdown and code interpretation
/// intact, and what keeps a byte-identical CSV/Markdown pair two
/// different readings of one blob.
///
/// Asked of an edition rather than globally because the answer is part
/// of what a generation recorded, not a property of today's binary: the
/// same path can be a sniffable candidate under `v6` and plain text
/// under `v7`, and each generation is read back under the one it was
/// written with.
pub(crate) fn path_names_text_family(edition: ExtractorEdition, path: &[u8]) -> bool {
    let Some(suffix) = path_suffix_lowercase(path) else {
        return false;
    };
    if edition.names_plain_text() && suffix == PLAIN_TEXT_EXTENSION.0 {
        return true;
    }
    EXTENSION_FAMILY
        .binary_search_by_key(&suffix.as_str(), |(ext, _)| ext)
        .is_ok()
}

/// Which extraction edition produced (or must validate) a generation.
///
/// P3 W3 extractor completion (`W3-EXTRACTOR-COMPLETION.md`, under
/// ruling 0095): the family vocabulary is a property of the *edition*
/// recorded on each generation, never a single global rule. That is what
/// lets `v3` widen coverage while every `v2` generation already staged in
/// an estate keeps validating and resolving byte-for-byte — the brief's
/// "preserve old generation objects and exact historical coordinate
/// resolution". `AtlasStore::validate_generation` resolves the edition
/// from `generation.extractor_set` and asks *it* for the family, rather
/// than re-deriving families from today's default.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ExtractorEdition {
    /// Historical: Rust and Markdown only. Never produced again; still
    /// validated and resolved.
    RustMarkdownV2,
    /// Historical: Markdown only.
    MarkdownOnlyV2,
    /// Historical: same content-family vocabulary as v3, packed one line
    /// per unit. Never produced again; still validated and resolved.
    ///
    /// The identity says `text-line-chunks` deliberately. This edition
    /// widens *which files are admitted*, not how they are cut: the
    /// unitizer is still `utf8-line-chunks-65536/v1`, so a unit is a
    /// bounded run of bytes on one line and nothing here claims to know
    /// a function, a class or a section. A reader must be able to tell
    /// that from the identity alone, without reading this file
    /// (`W3-EXTRACTOR-COMPLETION.md`: "Do not infer semantic syntax
    /// claims from line chunks ... keep extractor identities explicit").
    ContentFamiliesV3,
    /// Current. Same content-family vocabulary as v3, packed by bytes:
    /// consecutive short lines share a unit up to the 65536-byte budget
    /// `MULTILINE_UNITIZER_ID` names, rather than one unit per line
    /// regardless of length. This is what fixes `server.rs` — 16,857
    /// short lines that exceeded the per-blob unit-count budget under
    /// `v3` despite the blob itself sitting well under the byte budget
    /// (`W4-EXTRACTOR-MULTILINE.md`). Still text line chunks: a unit
    /// never claims to know a function, a class or a section, and a
    /// multi-line unit's `line_start`..`line_end` names exactly the
    /// lines it packs.
    ContentFamiliesV4,
    /// Same text vocabulary and chunking as `v4`, plus
    /// `ContentFamily::Document` for every extension
    /// `crate::document::format_for_path` admits. A document's bytes never
    /// reach the plain-text unitizer directly; `ExtractorPolicy::units`
    /// routes them through `crate::document::render` first, then chunks
    /// the resulting Markdown exactly as `v4` chunks any other text, under
    /// `DOCUMENT_MARKDOWN_UNITIZER_ID` rather than `v4`'s. Historical:
    /// admission here is decided from the path's extension alone, so a
    /// document carrying no recognized extension is never opened.
    DocumentsAnyDocV5,
    /// Current. Same vocabulary, chunking and document rendering as `v5`,
    /// with admission decided by `crate::document::resolved_format` rather
    /// than by the extension alone: a path neither vocabulary recognizes
    /// is screened on a bounded prefix
    /// (`crate::document::could_be_document`, `SNIFF_BYTES`) and admitted
    /// as `Document` only when `anydoc`'s own detector confirms it. An
    /// extensionless or deliberately mislabeled document is read for what
    /// it is; a path the text vocabulary already claims is still read as
    /// text, and an excluded path is still never opened.
    ///
    /// Historical: its vocabulary has no answer for `.txt`, so an
    /// ordinary plain-text file was screened as a possible container and
    /// — finding no container signature in prose — recorded
    /// `Unsupported`. `v7` is that correction.
    DocumentsDetectedV6,
    /// Current. `v6`'s admission, detection and chunking exactly, with
    /// one extension added to the text vocabulary: `.txt`.
    ///
    /// An ordinary glossary is read as the text it names rather than
    /// sniffed for a container it was never going to be, which is the
    /// text-family interpretation this reader is supposed to preserve.
    /// The
    /// widening is an edition and not a row in the shared table
    /// (`PLAIN_TEXT_EXTENSION`) for the reason editions exist at all: a
    /// generation `v6` recorded keeps validating and resolving exactly
    /// as it was written, including one whose `.txt` held real container
    /// bytes and was therefore recorded as a `Document` over its
    /// Markdown rendering.
    ///
    /// The trade `v7` accepts, said plainly: under this edition a `.txt`
    /// is text whatever its bytes hold, so a container deliberately
    /// saved under that name is indexed as its own markup rather than
    /// converted. That is the same rule `.md` and `.csv` have always
    /// had, and the name is the operator's own statement about the file.
    DocumentsDetectedTextV7,
}

impl ExtractorEdition {
    pub(crate) fn id(self) -> &'static str {
        match self {
            Self::RustMarkdownV2 => "utf8-lines/rust-markdown+utf8-line-chunks-65536/v2",
            Self::MarkdownOnlyV2 => "utf8-lines/markdown+utf8-line-chunks-65536/v2",
            Self::ContentFamiliesV3 => {
                "text-line-chunks/utf8-line-chunks-65536+semble-0.5.2-content-families/v3"
            }
            Self::ContentFamiliesV4 => {
                "text-multiline-chunks/utf8-multiline-chunks-65536+semble-0.5.2-content-families/v4"
            }
            Self::DocumentsAnyDocV5 => {
                "text-multiline-chunks/utf8-multiline-chunks-65536+semble-0.5.2-content-families+anydoc-0.2.4-documents/v5"
            }
            Self::DocumentsDetectedV6 => {
                "text-multiline-chunks/utf8-multiline-chunks-65536+semble-0.5.2-content-families+anydoc-0.2.4-detected-documents/v6"
            }
            Self::DocumentsDetectedTextV7 => {
                "text-multiline-chunks/utf8-multiline-chunks-65536+semble-0.5.2-content-families+txt+anydoc-0.2.4-detected-documents/v7"
            }
        }
    }
    /// The edition a *record* names — a generation's `extractor_set`, or
    /// a semantic edition's `ChunkerIdentity::extractor_set` — as the
    /// error a reader should report when this build does not know it.
    ///
    /// Every byte-reading path needs this before it can interpret a
    /// recorded resource at all, and "unknown edition" is a refusal
    /// rather than a fallback to today's rules: reading a generation
    /// under a vocabulary that is not the one it was written with is
    /// exactly the silent-wrong-bytes case editions exist to prevent.
    pub(crate) fn recorded(extractor_set: &str) -> Result<Self, crate::AtlasError> {
        Self::from_id(extractor_set).ok_or_else(|| {
            crate::AtlasError::Generation(format!(
                "recorded extraction edition {extractor_set} is not one this build can read"
            ))
        })
    }
    /// The inverse of `id`, for validating a generation against the
    /// edition it says produced it. An `extractor_set` naming no known
    /// edition is refused rather than silently validated under today's
    /// rules.
    pub(crate) fn from_id(id: &str) -> Option<Self> {
        [
            Self::RustMarkdownV2,
            Self::MarkdownOnlyV2,
            Self::ContentFamiliesV3,
            Self::ContentFamiliesV4,
            Self::DocumentsAnyDocV5,
            Self::DocumentsDetectedV6,
            Self::DocumentsDetectedTextV7,
        ]
        .into_iter()
        .find(|edition| edition.id() == id)
    }
    /// What this edition can decide about `path` **before any byte of it
    /// is read**. The first gate on every ingestion path, and the reason
    /// widening admission does not widen what gets opened: a path this
    /// answers `No` for is reported `Unsupported` without a read, exactly
    /// as it always was.
    pub(crate) fn admission(self, path: &[u8]) -> PathAdmission {
        if let Some(family) = self.path_family(path) {
            return PathAdmission::Family(family);
        }
        match self {
            // Only the detecting edition is willing to look further than
            // the name. Every historical edition keeps reading exactly the
            // paths it always did, so a generation staged under one still
            // re-verifies byte for byte.
            Self::DocumentsDetectedV6 | Self::DocumentsDetectedTextV7 => PathAdmission::Candidate,
            _ => PathAdmission::No,
        }
    }

    /// The family `path`'s extension names on its own, or `None` when the
    /// name settles nothing. Never sniffs.
    fn path_family(self, path: &[u8]) -> Option<ContentFamily> {
        match self {
            Self::RustMarkdownV2 => {
                if path.ends_with(b".md") {
                    Some(ContentFamily::Knowledge)
                } else if path.ends_with(b".rs") {
                    Some(ContentFamily::Code)
                } else {
                    None
                }
            }
            Self::MarkdownOnlyV2 => {
                if path.ends_with(b".md") {
                    Some(ContentFamily::Knowledge)
                } else {
                    None
                }
            }
            Self::ContentFamiliesV3 | Self::ContentFamiliesV4 => {
                let suffix = path_suffix_lowercase(path)?;
                EXTENSION_FAMILY
                    .binary_search_by_key(&suffix.as_str(), |(ext, _)| ext)
                    .ok()
                    .map(|index| EXTENSION_FAMILY[index].1)
            }
            Self::DocumentsAnyDocV5 | Self::DocumentsDetectedV6 | Self::DocumentsDetectedTextV7 => {
                if crate::document::format_for_path(path).is_some() {
                    return Some(ContentFamily::Document);
                }
                let suffix = path_suffix_lowercase(path)?;
                if self.names_plain_text() && suffix == PLAIN_TEXT_EXTENSION.0 {
                    return Some(PLAIN_TEXT_EXTENSION.1);
                }
                EXTENSION_FAMILY
                    .binary_search_by_key(&suffix.as_str(), |(ext, _)| ext)
                    .ok()
                    .map(|index| EXTENSION_FAMILY[index].1)
            }
        }
    }
    /// The family a resource is actually recorded under, decided from its
    /// name and — for the detecting edition, and only where the name
    /// settles nothing — its bytes. Every consumer that has the bytes in
    /// hand asks this rather than `path_family`, so capture, extraction,
    /// publish re-verification and the binary-blob screen all agree on one
    /// answer for one resource.
    pub(crate) fn family(self, path: &[u8], bytes: &[u8]) -> Option<ContentFamily> {
        if let Some(family) = self.path_family(path) {
            return Some(family);
        }
        match self {
            Self::DocumentsDetectedV6 | Self::DocumentsDetectedTextV7 => self
                .document_format(path, bytes)
                .map(|_| ContentFamily::Document),
            _ => None,
        }
    }
    /// Whether this edition's text vocabulary carries
    /// `PLAIN_TEXT_EXTENSION`. One place, because admission, the
    /// byte-level interpretation rule and the read-back path all have to
    /// give the same answer for one generation or its units index a
    /// string nothing can reproduce.
    pub(crate) fn names_plain_text(self) -> bool {
        matches!(self, Self::DocumentsDetectedTextV7)
    }
    /// Whether this edition packs consecutive short lines into one unit
    /// (`v4`/`v5`/`v6`) or bounds each unit to exactly one line
    /// (`v2`/`v3`, historical). Governs both the unitizer id units are
    /// stamped with and the chunking algorithm `ExtractorPolicy::units`
    /// runs.
    pub(crate) fn multiline(self) -> bool {
        matches!(
            self,
            Self::ContentFamiliesV4
                | Self::DocumentsAnyDocV5
                | Self::DocumentsDetectedV6
                | Self::DocumentsDetectedTextV7
        )
    }
    pub(crate) fn unitizer_id(self) -> &'static str {
        if self.multiline() {
            MULTILINE_UNITIZER_ID
        } else {
            UNITIZER_ID
        }
    }
    /// The `anydoc::Format` this edition reads a resource through, or
    /// `None` to fall through to the plain-text extractor. `v5` decides
    /// from the extension alone; `v6` defers to
    /// `crate::document::resolved_format`, which lets content override a
    /// misleading name and admit a document whose name says nothing.
    /// Every pre-document edition keeps reading exactly the paths it
    /// always did.
    pub(crate) fn document_format(self, path: &[u8], bytes: &[u8]) -> Option<anydoc::Format> {
        match self {
            Self::DocumentsAnyDocV5 => crate::document::format_for_path(path),
            Self::DocumentsDetectedV6 | Self::DocumentsDetectedTextV7 => {
                crate::document::resolved_format(self, path, bytes)
            }
            _ => None,
        }
    }
    /// The `(family, unitizer)` pair a recorded resource must carry under
    /// this edition, decided from its path alone, or `None` for a path
    /// this edition admits nothing at.
    ///
    /// This is what `validate_generation` checks a staged manifest
    /// against, and it is deliberately bytes-free: validation re-derives
    /// identity from the record, never from a second read of a source that
    /// may have moved on. Where the name settles the family, that family
    /// and its unitizer are the only admissible answer. Where the name
    /// settles nothing, the only way this edition admits a resource at all
    /// is by detecting a document in its content, so `Document` under the
    /// document unitizer is again the only admissible answer — a manifest
    /// claiming any other family for such a path is inconsistent with the
    /// edition it names, whatever the source now holds.
    pub(crate) fn recorded_shape(self, path: &[u8]) -> Option<(ContentFamily, &'static str)> {
        match self.admission(path) {
            PathAdmission::Family(ContentFamily::Document) => {
                Some((ContentFamily::Document, DOCUMENT_MARKDOWN_UNITIZER_ID))
            }
            PathAdmission::Family(family) => Some((family, self.unitizer_id())),
            PathAdmission::Candidate => {
                Some((ContentFamily::Document, DOCUMENT_MARKDOWN_UNITIZER_ID))
            }
            PathAdmission::No => None,
        }
    }
}

/// What a path alone settles about admission, before anything is opened.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub(crate) enum PathAdmission {
    /// The name decides: this family, no sniff.
    Family(ContentFamily),
    /// The name decides nothing. A bounded prefix
    /// (`crate::document::SNIFF_BYTES`) may be read and screened
    /// (`crate::document::could_be_document`); only if `anydoc`'s own
    /// detector then recognizes the content is this admitted, as
    /// `ContentFamily::Document`.
    Candidate,
    /// Not admitted, and not opened.
    No,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ExtractorPolicy {
    edition: ExtractorEdition,
}
impl Default for ExtractorPolicy {
    fn default() -> Self {
        Self {
            edition: ExtractorEdition::DocumentsDetectedTextV7,
        }
    }
}
impl ExtractorPolicy {
    pub fn markdown_only() -> Self {
        Self {
            edition: ExtractorEdition::MarkdownOnlyV2,
        }
    }
    /// The historical Rust+Markdown edition, kept constructible so a test
    /// can stage a `v2` generation on purpose and prove it still
    /// validates and resolves under the current binary.
    pub fn rust_markdown_v2() -> Self {
        Self {
            edition: ExtractorEdition::RustMarkdownV2,
        }
    }
    /// The historical one-line-per-unit `v3` edition, kept constructible
    /// so a test can stage it on purpose and prove it still validates and
    /// resolves under the current binary alongside `v4`.
    pub fn content_families_v3() -> Self {
        Self {
            edition: ExtractorEdition::ContentFamiliesV3,
        }
    }
    /// The historical `v4` edition (multiline text chunking, no document
    /// admission), kept constructible so a test can stage it on purpose
    /// and prove it still validates and resolves under the current
    /// binary alongside `v5`.
    pub fn content_families_v4() -> Self {
        Self {
            edition: ExtractorEdition::ContentFamiliesV4,
        }
    }
    pub(crate) fn id(&self) -> &str {
        self.edition.id()
    }
    /// The inverse of `id`/edition construction: reconstructs the exact
    /// `ExtractorPolicy` an already-staged generation's own
    /// `extractor_set` names, so a caller re-verifying that generation
    /// (`AtlasStore::publish_verify_doctree`) can re-run
    /// `doctree::capture`/`doctree::finish` under the identical edition
    /// rather than today's default — a `v2`/`v3` generation staged before the
    /// vocabulary widened must re-verify exactly as it was staged.
    /// `None` for an `extractor_set` naming no known edition, the same
    /// refusal `ExtractorEdition::from_id`'s existing callers already
    /// give.
    pub(crate) fn from_id(id: &str) -> Option<Self> {
        ExtractorEdition::from_id(id).map(|edition| Self { edition })
    }
    /// The historical `v5` edition (documents admitted by extension
    /// alone), kept constructible so a test can stage it on purpose and
    /// prove it still validates and resolves under the current binary
    /// alongside `v6`.
    pub fn documents_anydoc_v5() -> Self {
        Self {
            edition: ExtractorEdition::DocumentsAnyDocV5,
        }
    }
    /// The historical `v6` edition (documents detected from content, no
    /// `.txt` in the text vocabulary), kept constructible for the same
    /// reason `v5` is: a test stages one on purpose and proves it still
    /// validates and resolves byte-for-byte under a binary whose current
    /// edition answers `.txt` differently.
    pub fn documents_detected_v6() -> Self {
        Self {
            edition: ExtractorEdition::DocumentsDetectedV6,
        }
    }
    pub(crate) fn admission(&self, path: &[u8]) -> PathAdmission {
        self.edition.admission(path)
    }
    pub(crate) fn family(&self, path: &[u8], bytes: &[u8]) -> Option<ContentFamily> {
        self.edition.family(path, bytes)
    }
    pub(crate) fn excluded(path: &[u8]) -> bool {
        path.split(|b| *b == b'/')
            .any(|part| part == b".git" || part == b".env" || part == b"secret")
            || path.ends_with(b".pem")
            || path.ends_with(b".key")
    }
    pub(crate) fn units(
        &self,
        generation: &GenerationId,
        path: &[u8],
        object_id: &str,
        bytes: &[u8],
    ) -> Result<Vec<TextUnit>, String> {
        if let Some(format) = self.edition.document_format(path, bytes) {
            return self.document_units(generation, path, object_id, bytes, format);
        }
        let text = std::str::from_utf8(bytes).map_err(|_| "text blob is not valid UTF-8")?;
        let family = self
            .family(path, bytes)
            .ok_or("path has no configured content family")?;
        chunk_units(
            generation,
            path,
            object_id,
            bytes,
            text,
            family,
            self.edition.unitizer_id(),
            self.edition.multiline(),
        )
    }
    /// The `Document`-family counterpart of `units`: an admitted
    /// Office/PDF/CSV/OpenDocument/RTF/EPUB file's bytes never reach
    /// `chunk_units` themselves. They are first rendered to Markdown
    /// through `crate::document::render` — a scanned/malformed/
    /// encrypted input surfaces here as a truthful `Err`, the same
    /// `CoverageDisposition::Error` path a text-extraction failure
    /// already takes, never as an empty success — and only that
    /// Markdown is chunked, under `DOCUMENT_MARKDOWN_UNITIZER_ID` so a
    /// reader can tell from the unitizer id alone that offsets index
    /// converted text, not the original file
    /// (`ContentFamily::Document`'s doc comment).
    ///
    /// **No size gate on either side of the conversion, raw or
    /// rendered** (rulings 0398/0401/0403). Neither was a boundary this
    /// reader actually has. A raw-byte gate charged a container format
    /// for its compressed embedded media, which has nothing to do with
    /// how much text comes out — an image-heavy, text-light Office file
    /// would have been refused for a reason that never applied to its
    /// content. A gate on the *rendered* Markdown was a product-chosen
    /// "rendered-context budget" that turned an admitted, perfectly
    /// convertible document into a `CoverageDisposition::Error` with
    /// zero retrievable units: acquired, identified, and not indexed.
    ///
    /// What genuinely bounds a conversion is `anydoc` 0.2.4's own fixed
    /// safety limits (`anydoc::package::limits`, whose module doc states
    /// they are "deliberately not configurable": decompression size,
    /// entry count, XML depth and node count, grid slots, repeat
    /// expansion, retained asset bytes). Those surface through `render`
    /// as `ConvertError::ResourceLimit`, are exercised by the corpus's
    /// `06-hostile-entry-expansion.docx`/
    /// `17-pptx-hostile-entry-expansion.pptx` fixtures, and are reported
    /// here truthfully as the dependency's own refusal — alongside its
    /// malformed/encrypted/needs-OCR errors, which are equally real and
    /// equally preserved. What this reader does not do any more is add a
    /// number of its own on top of them.
    fn document_units(
        &self,
        generation: &GenerationId,
        path: &[u8],
        object_id: &str,
        bytes: &[u8],
        format: anydoc::Format,
    ) -> Result<Vec<TextUnit>, String> {
        let markdown = crate::document::render(format, bytes)?;
        chunk_units(
            generation,
            path,
            object_id,
            markdown.as_bytes(),
            &markdown,
            ContentFamily::Document,
            DOCUMENT_MARKDOWN_UNITIZER_ID,
            true,
        )
    }
    /// `acquisition_policy` is folded into the identity as an explicit
    /// parameter, so a generation binds the policy it was acquired
    /// under and can never collide with, or be mistaken for, a
    /// generation of the same source, revision, content and extractor
    /// acquired under a different one.
    pub(crate) fn generation_id(
        source: &str,
        revision: &str,
        content: &str,
        extractor: &str,
        acquisition_policy: &str,
    ) -> String {
        let mut h = Sha256::new();
        for part in [
            b"wirk-atlas-generation/v1".as_slice(),
            source.as_bytes(),
            revision.as_bytes(),
            content.as_bytes(),
            extractor.as_bytes(),
            acquisition_policy.as_bytes(),
        ] {
            h.update((part.len() as u64).to_be_bytes());
            h.update(part);
        }
        format!("g-{}", hex(&h.finalize()))
    }

    pub(crate) fn unit_id(
        generation: &GenerationId,
        path: &[u8],
        object_id: &str,
        family: ContentFamily,
        byte_start: u64,
        byte_end: u64,
        unitizer: &str,
    ) -> UnitId {
        let mut h = Sha256::new();
        for part in [
            b"wirk-atlas-unit/v1".as_slice(),
            generation.0.as_bytes(),
            path,
            object_id.as_bytes(),
            match family {
                ContentFamily::Code => b"code".as_slice(),
                ContentFamily::Knowledge => b"knowledge".as_slice(),
                // New in edition v3. A distinct tag, so a `config` unit
                // can never collide with a `code`/`knowledge` unit id.
                ContentFamily::Config => b"config".as_slice(),
                // New in edition v5. A distinct tag, so a `document`
                // unit (offsets into converted Markdown) can never
                // collide with a unit of any other family.
                ContentFamily::Document => b"document".as_slice(),
            },
            byte_start.to_string().as_bytes(),
            byte_end.to_string().as_bytes(),
            unitizer.as_bytes(),
        ] {
            h.update((part.len() as u64).to_be_bytes());
            h.update(part);
        }
        UnitId(format!("u-{}", hex(&h.finalize())))
    }
}

/// Shared by the plain-text path (`ExtractorPolicy::units`) and the
/// document path (`ExtractorPolicy::document_units`): splits `text` into
/// lines over `bytes`, then either packs consecutive short lines into
/// one unit up to `MAX_UNIT_BYTES` (`multiline`) or bounds each unit to
/// exactly one line, tagging every resulting unit with `family` and
/// `unitizer`. `bytes` and `text` must be the same content — `bytes` for
/// the line/offset arithmetic, `text` because line-splitting a mid-line
/// chunk has to stay on a UTF-8 boundary.
#[allow(clippy::too_many_arguments)]
fn chunk_units(
    generation: &GenerationId,
    path: &[u8],
    object_id: &str,
    bytes: &[u8],
    text: &str,
    family: ContentFamily,
    unitizer: &str,
    multiline: bool,
) -> Result<Vec<TextUnit>, String> {
    let mut lines: Vec<(usize, usize, u64)> = Vec::new();
    let mut start = 0usize;
    let mut line = 1u64;
    for (index, byte) in bytes.iter().enumerate() {
        if *byte == b'\n' {
            lines.push((start, index + 1, line));
            start = index + 1;
            line += 1;
        }
    }
    if start < bytes.len() || bytes.is_empty() {
        lines.push((start, bytes.len(), line));
    }
    let mut units = Vec::new();
    if multiline {
        let mut chunk: Option<(usize, u64, usize, u64)> = None; // (byte_start, line_start, byte_end, line_end)
        for (line_start, line_end, line_no) in lines {
            if line_end - line_start > MAX_UNIT_BYTES {
                if let Some((cs, csl, ce, cel)) = chunk.take() {
                    push_unit(
                        &mut units, generation, path, object_id, family, unitizer, cs, ce, csl, cel,
                    );
                }
                push_line_chunks(
                    &mut units, text, line_start, line_end, line_no, generation, path, object_id,
                    family, unitizer,
                )?;
                continue;
            }
            chunk = Some(match chunk {
                None => (line_start, line_no, line_end, line_no),
                Some((cs, csl, _, _)) if line_end - cs > MAX_UNIT_BYTES => {
                    push_unit(
                        &mut units,
                        generation,
                        path,
                        object_id,
                        family,
                        unitizer,
                        cs,
                        line_start,
                        csl,
                        line_no - 1,
                    );
                    (line_start, line_no, line_end, line_no)
                }
                Some((cs, csl, _, _)) => (cs, csl, line_end, line_no),
            });
        }
        if let Some((cs, csl, ce, cel)) = chunk {
            push_unit(
                &mut units, generation, path, object_id, family, unitizer, cs, ce, csl, cel,
            );
        }
    } else {
        for (line_start, line_end, line_no) in lines {
            push_line_chunks(
                &mut units, text, line_start, line_end, line_no, generation, path, object_id,
                family, unitizer,
            )?;
        }
    }
    Ok(units)
}

#[allow(clippy::too_many_arguments)]
fn push_line_chunks(
    units: &mut Vec<TextUnit>,
    text: &str,
    line_start: usize,
    line_end: usize,
    line: u64,
    generation: &GenerationId,
    path: &[u8],
    object_id: &str,
    family: ContentFamily,
    unitizer: &str,
) -> Result<(), &'static str> {
    if line_start == line_end {
        push_unit(
            units, generation, path, object_id, family, unitizer, 0, 0, line, line,
        );
        return Ok(());
    }
    let mut start = line_start;
    while start < line_end {
        let mut end = (start + MAX_UNIT_BYTES).min(line_end);
        while end > start && !text.is_char_boundary(end) {
            end -= 1;
        }
        if end == start {
            return Err("UTF-8 codepoint exceeds unit size budget");
        }
        push_unit(
            units, generation, path, object_id, family, unitizer, start, end, line, line,
        );
        start = end;
    }
    Ok(())
}

#[allow(clippy::too_many_arguments)]
fn push_unit(
    units: &mut Vec<TextUnit>,
    generation: &GenerationId,
    path: &[u8],
    object_id: &str,
    family: ContentFamily,
    unitizer: &str,
    byte_start: usize,
    byte_end: usize,
    line_start: u64,
    line_end: u64,
) {
    // No unit-count ceiling. It was the same size-derived refusal
    // `MAX_TEXT_BYTES` was, one step later and expressed in a different
    // unit: crossing it produced exactly the empty-units
    // `CoverageDisposition::Error` rulings 0402/0403 name, for admitted
    // text whose only fault was being long. How many units a blob makes
    // is a fact about the blob, not a capability of this reader.
    units.push(TextUnit {
        id: ExtractorPolicy::unit_id(
            generation,
            path,
            object_id,
            family,
            byte_start as u64,
            byte_end as u64,
            unitizer,
        ),
        family,
        unitizer: unitizer.into(),
        byte_start: byte_start as u64,
        byte_end: byte_end as u64,
        line_start,
        line_end,
    });
}

fn hex(bytes: &[u8]) -> String {
    bytes.iter().map(|byte| format!("{byte:02x}")).collect()
}
